version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: nexora-postgres
    environment:
      POSTGRES_DB: nexora_db
      POSTGRES_USER: nexora
      POSTGRES_PASSWORD: nexora_secret
    ports:
      - "5432:5432"
    volumes:
      - nexora_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexora -d nexora_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  nexora_pg_data:
